#!/bin/bash
set -e #in case of any error exist

#checking that sufficient space is present to install all the file system
spaceLeft=$(df $PWD | awk '/[0-9]%/{print $(NF-2)}')
spaceConsumed=2000000	# PAL USB + ROS takes 2.4 GB of space. PAL-USB only takes 1.7 GB space

spaceLeftAfterInstallation=$(expr $spaceLeft - $spaceConsumed)

if [[ $spaceLeftAfterInstallation -lt 0 ]]; then
	exit 1;
fi
#end

#start of setup_python_env.sh
mkdir -p /home/$SUDO_USER/DreamVu/
cd /home/$SUDO_USER/DreamVu/

	
python3 -m venv dreamvu_ws
source ./dreamvu_ws/bin/activate
pip install --upgrade setuptools pip
pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
pip install -U grpcio absl-py 
pip install Cython
pip install numpy==1.19.3
pip uninstall opencv-python-headless
pip install pyyaml imageio opencv-python==4.5.3.56
pip install pyparsing==3.0.8
pip install catkin_pkg
pip install empy 
pip install Xlib
#end of setup_python_env.sh


echo "export LD_LIBRARY_PATH=$"LD_LIBRARY_PATH":/usr/local/lib" >> /home/$SUDO_USER/.bashrc
echo "source `pwd`/dreamvu_ws/bin/activate" >> /home/$SUDO_USER/.bashrc

#save the activation files
#logic: Activation files are moved to location /home/$SUDO_USER/DreamVu/activation_pal/
# activation will be called inside the deb files

cd /
tar -xzf /activation_arm64_pal.tar.gz 
cd /activation_arm64_pal
chmod +x *.sh
mkdir -p /usr/local/bin/data
cp /activation_arm64_pal/*.json /usr/local/bin/data
chown -R $SUDO_USER:$SUDO_USER /usr/local/bin/data/*.json
mkdir -p /home/$SUDO_USER/DreamVu/activation_pal/
rsync -a /activation_arm64_pal/* /home/$SUDO_USER/DreamVu/activation_pal/

cd ..

rm -rf /activation_arm64_pal
rm /activation_arm64_pal.tar.gz


source /home/$SUDO_USER/DreamVu/dreamvu_ws/bin/activate
cd /

#test_py_installations.py
python test_py_installations_pal.py
rm test_py_installations_pal.py


# start of timeout_patch.sh
chmod +x rc_pal.local
sudo cp rc_pal.local /etc/rc.local
sudo chmod +x /etc/rc.local
rm rc_pal.local
# end

#copy systemd service to enable jetson clocks
sudo cp run_jetson_clocks_pal.service /lib/systemd/system/run_jetson_clocks.service
rm run_jetson_clocks_pal.service

#start of pal_undev
MY_PROMPT='$ '

echo 
echo "Creating Udev rules for PAL camera";

echo "KERNEL==\"video*\", SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"2560\", ATTR{index}==\"0\", ATTRS{manufacturer}==\"e-con systems\", SYMLINK+=\"video5\"" >/etc/udev/rules.d/pal.rules

echo "SUBSYSTEM==\"hid*\", ATTRS{idVendor}==\"2560\", MODE=\"0666\", SYMLINK+=\"hid5\"" >>/etc/udev/rules.d/pal.rules


echo "Udev rule created for PAL Camera";
echo 
#end

sudo ldconfig

exit 0
