#!/bin/bash
sudo wget -qO - https://dreamvu.github.io/ppa/KEY.gpg | sudo apt-key add -
sudo wget -qO /etc/apt/sources.list.d/dreamvu.list https://dreamvu.github.io/ppa/dreamvu.list
sudo apt update
sudo apt install pal-usb
